# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170205_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
